# Site settings
title: KnightKrawler Robotics
description: FRC 2052 - Irondale Robotics Team - KnightKrawler
cover: assets/images/2018-TeamPhoto.png
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://frc2052.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: team2052
twitter: team2052
github:  frc2052

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: samanyougarg #github username
repo: hanuman #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml